sudo: required

services:
    - docker

before_install:
    - docker build -t sijojosan/message-board-ui_dev -f ./message-board-ui/Dockerfile.dev ./message-board-ui
    - docker build -t sijojosan/message-board-service_dev -f ./message-board-service/Dockerfile.dev ./message-board-service

script:
    - docker run -e CI=true sijojosan/message-board-ui_dev npm test
    - docker run sijojosan/message-board-service_dev mvn test

after_success:
    - docker build -t sijojosan/message-board-ui ./message-board-ui
    - docker build -t sijojosan/message-board-service ./message-board-service
    - docker build -t sijojosan/message-board-nginx ./nginx
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push sijojosan/message-board-ui
    - docker push sijojosan/message-board-service
    - docker push sijojosan/message-board-nginx
    
deploy:
  edge: true  
  provider: elasticbeanstalk
  region: us-east-1
  app: message-board
  env: MessageBoard-env-3
  bucket_name: elasticbeanstalk-us-east-1-660893847153
  bucket_path: message-board-3
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
